[package]
name = "rust_i2c_bmp280"
version = "0.1.0"
edition = "2021"

[dependencies]
linux-embedded-hal = "0.4.0"  # For I2C communication on Linux
bme280 = "0.5.1"              # BME280/BMP280 driver
