[package]
name = "rust_i2c_ina219"
version = "0.1.0"
edition = "2021"

[dependencies]
linux-embedded-hal = "0.4.0"  # For I2C communication on Linux
ina219 = "0.2.0"              # For interacting with the INA219 sensor
