name: Rust ARM64 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-unknown-linux-gnu

      - name: Install ARM64 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libclang-dev
          git clone --depth=1 https://github.com/seandepagnier/RTIMULib2
          pwd
          ln -s ${HOME}/work/RTIMULib2/RTIMULib ${HOME}/work/bbn_rust_sandbox/RTIMULib

      - name: Build the project
        run: |
          for d in  `find . -type d -name rust_i2c\* -not -name rust_i2c_bme680`; do
          echo $d
          cd $d
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          pwd
          cargo build --release --target aarch64-unknown-linux-gnu
          cd ..
          done

